### ISSUE TITLE
Regression: Java Constructors no longer validate

### ISSUE THREAD

**Issue by F43nd1r** [google/ksp#1061]
The constructor of the following type no longer validates in 1.7 versions

```kotlin
    @ApplicationCommand
    @Value
    public class ListData {
        @NonNull ScPuzzle puzzle;

        public ListData(ScPuzzle puzzle) {
            this.puzzle = puzzle;
        }
    }
```

Last known working version: 1.6.21-1.0.5
Debugging into the processor shows that the constructor return type as well as parameter types are error types in this case.

Kotlin classes with the same annotation validate without issue.

Possibly related issues: #961, #489

**Comment by neetopia** [comment]
this looks to be like an issue similar to what #1049 is trying to fix, and we've published a snapshot build containing that fix, can you verify if it solves your issue?

**Comment by F43nd1r** [comment]
Tested with `1.7.20-Beta-1.0.7-SNAPSHOT`, I assume that is the mentioned snapshot? Did not fix the issue.

**Comment by neetopia** [comment]
can you give a full picture of your code? I tried following test case on my side and it validates normally.
```
// FILE: ListJava.java

public class ListJava {
    String str;

    public ListJava(String s) {
        this.str = s;
    }
}

```

`listJava.getConstructors().forEach { validate(it) }` returns `true` for me.

**Comment by neetopia** [comment]
I am more interested in the actual workload, the logic that fails is same as mine, so I doubt it is the workload that causes failure, as I see in your sample above there is a `ScPuzzle` in the constructor parameter which is what I can't reproduce on my side without more context.

**Comment by F43nd1r** [comment]
The given example was simplified from this https://github.com/F43nd1r/zachtronics-leaderboard-bot/blob/2ac2d9b3581c20c849b808261bd12a6ec4ac8bf5/src/main/java/com/faendir/zachtronics/bot/sc/discord/ScListCommand.java#L57

**Comment by ting-yuan** [comment]
I cannot reproduce as well. Since the reporter isn't blocked on this, I'm removing it from the milestone.
