### ISSUE TITLE
KSP2: KSClassDeclaration.getSealedSubclasses for symbols defined in sources

### ISSUE THREAD

**Issue by ting-yuan** [google/ksp#1643]

**Comment by neetopia** [comment]
it is fixed by latest compiler update.

**Comment by ZacSweers** [comment]
I'm still seeing 0 sealed subclasses returned in 2.0.0-Beta5-1.0.20

**Comment by neetopia** [comment]
Thanks for the repo, I will investigate it.

**Comment by neetopia** [comment]
has there been any changes to moshix regarding the test mentioned in this issue? I tried to pull the PR to my local and `MoshiProguardGenSymbolProcessorTest` is passing for me.

**Comment by ZacSweers** [comment]
It seems to be working now, I'm not sure what changed. Sorry forgot to update here!

**Comment by neetopia** [comment]
Thanks for confirming, I will close this issue since it is resolved now.
