### ISSUE TITLE
[KSP2] Calling getDeclarationsInSourceOrder throws KotlinIllegalStateExceptionWithAttachments

### ISSUE THREAD

**Issue by kuanyingchou** [google/ksp#1930]
This is another test case in XProcessing. Calling `getDeclarationsInSourceOrder` on a Java class implementing a Kotlin interface throws KotlinIllegalStateExceptionWithAttachments. If the sources are compiled then it works.

Repro: https://github.com/kuanyingchou/ksp/commit/d4962e8ad609b74c0d17ab940d23e0843cab2ea4

**Comment by neetopia** [comment]
This issue appears to have been fixed, can you help me confirm?

**Comment by neetopia** [comment]
maybe not, but I can't seem to reproduce the issue with your repro.

**Comment by kuanyingchou** [comment]
Oops, sorry I moved the files to a lib module to test compiled origins and forgot to move them back. I just tried the latest main and can still reproduce.

**Comment by neetopia** [comment]
created upstream issue for this: https://youtrack.jetbrains.com/issue/KT-69070

**Comment by neetopia** [comment]
Simply removing this line seems to help: https://github.com/JetBrains/kotlin/blob/cff91084f650490747a650869cbf9e3e316f1e93/compiler/fir/providers/src/org/jetbrains/kotlin/fir/scopes/impl/FirFakeOverrideGenerator.kt#L668

on the other hand, in the debugger, at the exception site, the status of the fir symbol is in resolve phase of `TYPE` which caused the failure in check.

**Comment by kuanyingchou** [comment]
It seems that the Kotlin parent has to be generic. Here's another repro with `declarations` call:
https://github.com/kuanyingchou/ksp/commit/9deb6043c1875276f50a478dc27d1b799b74b732

**Comment by ting-yuan** [comment]
The upstream issue was fixed last week and we are waiting for the next compiler update. build-2.1.0-dev-4693

**Comment by ting-yuan** [comment]
Verified with Kotlin 2.1.0-dev-5441.
