### ISSUE TITLE
Project Isolation: Project cannot access task dependencies directly

### ISSUE THREAD

**Issue by consp1racy** [google/ksp#1943]
`buildDependencies.getDependencies(null)` isn't compatible with Project Isolation.

> ⌄⨉Project :app cannot access task dependencies directly
⌄plugin 'org.jetbrains.kotlin.android'
›Exception at com.google.devtools.ksp.gradle.KspGradleSubplugin.applyToCompilation$configureAsAbstractKotlinCompileTool(KspSubplugin.kt:322)
›Exception at com.google.devtools.ksp.gradle.KspSubpluginKt.nonSelfDeps(KspSubplugin.kt:864)

https://github.com/google/ksp/blob/d8efe453f331f0568ffc8c3f2f64a1cbbd951a81/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L300-L332

https://github.com/google/ksp/blob/d8efe453f331f0568ffc8c3f2f64a1cbbd951a81/gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt#L863-L866

https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ReportingTaskDependencyUsageTracker.kt

I'm looking for a PI-compatible alternative API. Or waiting for the Gradle team to make the exiting API compatible ^^

---

Reading properties from parent projects can be prevented by assigning same-named extras on every project using KSP. That's another problem, that can already be worked around.

**Comment by martinbonnin** [comment]
+1 to this issue. Bellow a configuration cache reports that lists `cannot access task dependencies directly` issues as well  as `cannot dynamically look up a property in the parent project` on `ksp.experimental.processing.model` and a bunch of others.

[cache-report.zip](https://github.com/user-attachments/files/16202797/cache-report.zip)

**Comment by ansman** [comment]
The `cannot dynamically look up a property in the parent project` errors have been fixed in #2034

**Comment by solonovamax** [comment]
> The `cannot dynamically look up a property in the parent project` errors have been fixed in [#2034](https://github.com/google/ksp/pull/2034)

Which release is this a part of?

**Comment by liutikas** [comment]
More of Stacktraces for the two issues remaining:
```
org.gradle.api.InvalidUserCodeException: Project ':room:integration-tests:room-testapp-multiplatform' cannot access task dependencies directly
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.reportProjectIsolationProblemOnApiUsage(ReportingTaskDependencyUsageTracker.kt:57)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.onTaskDependencyUsage(ReportingTaskDependencyUsageTracker.kt:37)
	at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:64)
	at com.google.devtools.ksp.gradle.KspSubpluginKt.nonSelfDeps(KspSubplugin.kt:932)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1$1$1.invoke(KspAATask.kt:184)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1$1$1.invoke(KspAATask.kt:173)
	at org.jetbrains.kotlin.gradle.utils.MutableObservableSetImpl.forAll(ObservableSet.kt:96)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:173)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:159)
	at com.google.devtools.ksp.gradle.KspAATask$Companion.registerKspAATask$lambda$1(KspAATask.kt:159)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

and
```
org.gradle.api.InvalidUserCodeException: Project ':room:integration-tests:room-testapp-multiplatform' cannot access task dependencies directly
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.reportProjectIsolationProblemOnApiUsage(ReportingTaskDependencyUsageTracker.kt:57)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.onTaskDependencyUsage(ReportingTaskDependencyUsageTracker.kt:37)
	at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:64)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:172)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:159)
	at com.google.devtools.ksp.gradle.KspAATask$Companion.registerKspAATask$lambda$1(KspAATask.kt:159)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by solrudev** [comment]
This was fixed in #2713.

**Comment by matejdro** [comment]
I'm still seeing those errors with `2.3.4` that is supposed to contain #2713

```
org.gradle.api.InvalidUserCodeException: Project ':common-compose' cannot access task dependencies directly

	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1$build$diagnostics$1.get(DefaultProblemFactory.kt:89)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.getImplicitThrowable(DefaultProblemDiagnosticsFactory.java:165)
	at org.gradle.internal.problems.DefaultProblemDiagnosticsFactory$DefaultProblemStream.forCurrentCaller(DefaultProblemDiagnosticsFactory.java:154)
	at org.gradle.internal.configuration.problems.DefaultProblemFactory$problem$1.build(DefaultProblemFactory.kt:89)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.reportProjectIsolationProblemOnApiUsage(ReportingTaskDependencyUsageTracker.kt:57)
	at org.gradle.internal.cc.impl.ReportingTaskDependencyUsageTracker.onTaskDependencyUsage(ReportingTaskDependencyUsageTracker.kt:37)
	at org.gradle.api.internal.tasks.AbstractTaskDependency.getDependencies(AbstractTaskDependency.java:64)

	at com.google.devtools.ksp.gradle.KspSubpluginKt.nonSelfDeps(KspSubplugin.kt:466)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1$3$1.invoke(KspAATask.kt:217)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1$3$1.invoke(KspAATask.kt:201)
	at org.jetbrains.kotlin.gradle.utils.MutableObservableSetImpl.forAll(ObservableSet.kt:96)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:201)
	at com.google.devtools.ksp.gradle.KspAATask$Companion$registerKspAATask$kspTaskProvider$1.invoke(KspAATask.kt:189)
	at com.google.devtools.ksp.gradle.KspAATask$Companion.registerKspAATask$lambda$2(KspAATask.kt:189)
```

EDIT: Ah, it's an opt in. You have to set `ksp.project.isolation.enabled=true` gradle property.

**Comment by trobalik-duolingo** [comment]
Is this documented anywhere besides this issue?
> EDIT: Ah, it's an opt in. You have to set ksp.project.isolation.enabled=true gradle property.

**Comment by jaschdoc** [comment]
Are you still experiencing this issue?

**Comment by trobalik-duolingo** [comment]
> Are you still experiencing this issue?

Setting the property resolved the problem for me. I was only asking for a reference in the documentation, since linking to a comment on a GH issue (when discussing with my team) didn't feel very robust.

**Comment by jaschdoc** [comment]
Alright, great to hear. Thanks for the feedback! We should indeed update the documentation.

**Comment by jaschdoc** [comment]
The readme has been updated :)

**Comment by trobalik-duolingo** [comment]
Thanks! I just checked and I see this in the table:
```
Enables Gradle Project Isolation compatible codepaths for output directory registration. NOTE: KSP also enables this if you have org.gradle.unsafe.isolated-projects=true or org.gradle.isolated-projects=true configured.
```
However, I'm not sure that's true? At least, I found this issue when I used Gradle 9.7.0-rc-1 and added `org.gradle.isolated-projects=true`.

Also, and this is tangential, but I'm curious why this is an opt-in? Are you just unsure if it'll break something?

**Comment by ChristianKatzmann** [comment]
> At least, I found this issue when I used Gradle 9.7.0-rc-1 and added org.gradle.isolated-projects=true.

This was implemented in https://github.com/google/ksp/pull/3051 which got merged two days ago and wasn't released yet. In the released version, the `.unsafe.` variant should work, though.
