### ISSUE TITLE
KSP uses kotlin.sourceSets DSL when using AGP Built-In Kotlin

### ISSUE THREAD

**Issue by pablobaxter** [google/ksp#2729]
In AGP 9.0.0-beta05, the following error is seen during configuration phase of a build using KSP:

```
> com.android.builder.errors.EvalIssueException: Using kotlin.sourceSets DSL to add Kotlin sources is not allowed with built-in Kotlin.
  Kotlin source set 'canary' contains: [/private/var/folders/nf/zd81923n2m367tmljt5d95l00000gp/T/junit5050839223032315639/build/generated/ksp/canary/kotlin, /private/var/folders/nf/zd81923n2m367tmljt5d95l00000gp/T/junit5050839223032315639/build/generated/ksp/canary/java]
  Solution: Use android.sourceSets DSL instead.
  For more information, see https://developer.android.com/r/tools/built-in-kotlin
  To suppress this error, set android.disallowKotlinSourceSets=false in gradle.properties.
```

The flag `android.disallowKotlinSourceSets=false` does resolve this issue.

**Comment by FooIbar** [comment]
I think it's fixed by #2725 ?

**Comment by pablobaxter** [comment]
Just tested `2.3.4-SNAPSHOT` and still seeing the same issue.

**Comment by FooIbar** [comment]
So I checked the [sources.jar](https://central.sonatype.com/repository/maven-snapshots/com/google/devtools/ksp/symbol-processing-gradle-plugin/2.3.4-SNAPSHOT/symbol-processing-gradle-plugin-2.3.4-20251211.110754-25-sources.jar) and found it's identical with the `2.3.4-release` branch, instead of `main` (which, kinda makes sense because it literally has `2.3.4` in its name).

**Comment by pablobaxter** [comment]
Good catch! I'll build KSP locally and re-test.

**Comment by pablobaxter** [comment]
Looks like it's fixed in the latest from `main`. Thanks!

**Comment by FooIbar** [comment]
@ting-yuan For future reference, is there any way for us to get the snapshot builds for the `main` branch?

**Comment by hfmehmed** [comment]
Usually PRs merged in main go to the next snapshot release branch (2.3.4-release in this case) but there has been a problem with that infrastructure it seems. I will fix it. Thanks for the heads up

**Comment by hfmehmed** [comment]
Should be fixed now, you can try with 2.3.4-SNAPSHOT and let me know

**Comment by FooIbar** [comment]
Verified 2.3.4-SNAPSHOT is working now, thanks!
